CREATE TABLE public.reasons (
  id uuid not null default gen_random_uuid() primary key,
  order_index integer not null default 0,
  text text not null default '',
  created_at timestamptz not null default now()
);

GRANT SELECT ON public.reasons TO anon, authenticated;
GRANT ALL ON public.reasons TO service_role;

ALTER TABLE public.reasons ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anyone can read reasons" ON public.reasons FOR SELECT USING (true);

CREATE INDEX reasons_order_idx ON public.reasons(order_index);

INSERT INTO public.reasons (order_index, text) VALUES
(1, 'Kepribadian kamu yang luar biasa dan penuh keindahan'),
(2, 'Senyuman kamu yang selalu bisa mencairkan hatiku'),
(3, 'Pemikiran kamu yang dalam, bijak, dan selalu mengejutkanku'),
(4, 'Kedewasaan kamu dalam menghadapi setiap situasi'),
(5, 'Caramu memandangku — seperti aku adalah seluruh duniamu'),
(6, 'Kesabaran kamu yang nyaris tak berbatas'),
(7, 'Keistimewaan kamu yang tak tertandingi oleh siapapun'),
(8, 'Kamu adalah sahabat terbaikku, sebelum menjadi cintaku'),
(9, 'Kamu mendengarkanku dengan tulus, tanpa menghakimi'),
(10, 'Sikap positif kamu yang selalu menularkan semangat'),
(11, 'Kamu sangat peduli — pada aku, pada orang lain, pada hal-hal kecil sekalipun'),
(12, 'Kamu adalah tempat ternyamanku di seluruh dunia ini'),
(13, 'Kamu adalah tempat teraman yang pernah aku temukan'),
(14, 'Kamu mendukung setiap impianku tanpa pernah ragu'),
(15, 'Kamu adalah penyemangat terbesar yang pernah aku miliki'),
(16, 'Cara kamu tertawa — tulus, lepas, dan selalu membuat hatiku ikut bahagia'),
(17, 'Kamu selalu hadir di saat aku paling membutuhkan, tanpa perlu aku minta'),
(18, 'Kamu membuatku menjadi versi terbaik dari diri aku sendiri'),
(19, 'Cara kamu mengungkapkan rasa peduli lewat tindakan kecil yang bermakna besar'),
(20, 'Ketulusan kamu dalam mencintai — tidak ada yang dibuat-buat'),
(21, 'Cara kamu memahami perasaanku bahkan sebelum aku mengucapkannya'),
(22, 'Matamu yang berbicara lebih banyak dari kata-kata manapun'),
(23, 'Kehangatan yang selalu bisa aku rasakan setiap kali bersamamu'),
(24, 'Cara kamu menyebut namaku — ada sesuatu yang berbeda saat kamu yang mengatakannya'),
(25, 'Kamu membuat hari-hari biasa terasa sangat luar biasa'),
(26, 'Kepekaan kamu terhadap perasaan orang lain yang selalu membuatku kagum'),
(27, 'Cara kamu mengingat hal-hal kecil yang penting bagiku'),
(28, 'Kamu tidak pernah lelah mendengar ceritaku, bahkan yang paling sepele sekalipun'),
(29, 'Kamu selalu jujur, bahkan ketika kejujuran itu tidak mudah'),
(30, 'Cara kamu memelukku — hangat, erat, dan selalu terasa seperti pulang ke rumah'),
(31, 'Kamu mengajarkan aku artinya benar-benar bersyukur'),
(32, 'Semangat kamu yang selalu berhasil menginspirasi aku untuk terus maju'),
(33, 'Cara kamu menghadapi masalah dengan kepala dingin dan hati yang tenang'),
(34, 'Kamu tidak pernah menyerah — pada diri sendiri, pada kita, pada keadaan'),
(35, 'Kemandirian kamu yang sangat aku kagumi dan banggakan'),
(36, 'Cara kamu tersenyum waktu setengah mengantuk — itu salah satu pemandangan terindah'),
(37, 'Kamu tahu persis kapan aku butuh ruang, dan kapan aku butuh dipeluk'),
(38, 'Cara kamu tetap lembut, bahkan di saat keadaan tidak memihak kamu sekalipun'),
(39, 'Kamu adalah orang yang paling aku percaya di seluruh dunia ini'),
(40, 'Cara kamu selalu melihat sisi baik dari setiap situasi, seberat apapun itu'),
(41, 'Kamu selalu mencoba memahami sudut pandang orang lain sebelum menghakimi'),
(42, 'Rasa ingin tahu kamu yang membuat percakapan kita tidak pernah membosankan'),
(43, 'Cara kamu berpikir — terstruktur, kreatif, dan selalu berhasil mengejutkanku'),
(44, 'Kamu tidak pernah membuat aku merasa sendirian, meski aku sedang jauh'),
(45, 'Selera humor kamu yang selalu bisa membuat aku senyum sendiri tiba-tiba'),
(46, 'Cara kamu mengambil keputusan — penuh pertimbangan namun tetap berani'),
(47, 'Kamu membuat aku berani bermimpi lebih besar dari yang pernah aku bayangkan'),
(48, 'Cara kamu merawat diri sendiri — aku belajar banyak tentang menghargai diri dari kamu'),
(49, 'Kamu mengajarkan aku bahwa cinta yang nyata tidak harus sempurna'),
(50, 'Cara kamu mengekspresikan diri — autentik, jujur, dan tanpa topeng apapun'),
(51, 'Kamu tidak pernah berpura-pura menjadi orang lain di depanku'),
(52, 'Cara kamu merawat hubungan kita dengan penuh perhatian dan kesungguhan'),
(53, 'Kepercayaan kamu padaku, bahkan di saat aku sendiri meragukan kemampuan diri'),
(54, 'Cara kamu bilang "aku bangga sama kamu" — selalu tepat di waktu yang paling aku butuhkan'),
(55, 'Kamu adalah alasan aku selalu pulang dengan hati yang lebih ringan'),
(56, 'Cara kamu berdebat — sehat, adil, dan tidak pernah menyakiti'),
(57, 'Kamu selalu mau belajar dan berkembang, tidak pernah merasa sudah cukup'),
(58, 'Cara kamu merayakan keberhasilan aku — seolah-olah itu adalah milikmu juga'),
(59, 'Kamu tidak pernah membuatku merasa kecil atau tidak cukup baik'),
(60, 'Cara kamu berterima kasih untuk hal-hal sekecil apapun — itu mengajarkanku banyak'),
(61, 'Kamu mengajarkan aku cara mencintai tanpa syarat dan tanpa hitungan'),
(62, 'Cara kamu menjaga kepercayaan — tidak pernah sekalipun aku meragukannya'),
(63, 'Kamu hadir sepenuhnya saat bersamaku — dunia luar bisa menunggu'),
(64, 'Cara kamu memperhatikan detail kecil tentang aku yang bahkan aku sendiri sering lupakan'),
(65, 'Kamu adalah cermin yang selalu menunjukkan sisi terbaik dari diri aku'),
(66, 'Cara kamu bilang "aku di sini ya" — sederhana, tapi selalu lebih dari cukup'),
(67, 'Kamu membuat diam di antara kita pun terasa nyaman dan tidak canggung'),
(68, 'Cara kamu mencintai hal-hal yang aku cintai, hanya karena aku mencintainya'),
(69, 'Kamu tidak pernah meremehkan atau mengecilkan perasaanku'),
(70, 'Cara kamu menghiburku — tidak selalu dengan solusi, tapi dengan kehadiran yang tulus'),
(71, 'Kamu adalah orang yang setiap harinya membuatku ingin menjadi lebih baik'),
(72, 'Cara kamu berkomitmen pada hal-hal yang kamu yakini — aku sangat menghormati itu'),
(73, 'Kamu selalu menghargai usahaku, sekecil dan sesederhana apapun itu'),
(74, 'Cara kamu menjaga perasaanku bahkan di saat kamu sendiri sedang tidak baik-baik saja'),
(75, 'Kamu mengajarkan aku bahwa kerentanan dan kejujuran adalah bentuk keberanian'),
(76, 'Cara kamu menatapku saat aku sedang berbicara — sepenuh hati, tanpa terganggu apapun'),
(77, 'Kamu adalah alasan di balik senyum terbaikku — yang tulus, bukan yang dipaksakan'),
(78, 'Cara kamu hadir secara emosional, tidak hanya secara fisik'),
(79, 'Kamu selalu mencari cara untuk membuat hariku lebih baik, bahkan dari hal terkecil'),
(80, 'Cara kamu memaafkan — tulus, tanpa menghitung-hitung, tanpa menyimpan dendam'),
(81, 'Kamu adalah orang pertama yang ingin aku hubungi saat ada berita baik maupun buruk'),
(82, 'Cara kamu menghargai dan mengapresiasi orang-orang di sekitar kamu'),
(83, 'Kamu membuat aku merasa dilihat, didengar, dan sungguh-sungguh dihargai'),
(84, 'Cara kamu tetap cantik bahkan saat sedang lelah atau sedang marah sekalipun'),
(85, 'Kamu mengajarkan aku seperti apa hubungan yang sehat dan nyata itu seharusnya'),
(86, 'Cara kamu mengucapkan namaku — ada resonansi yang berbeda yang tidak bisa aku jelaskan'),
(87, 'Kamu adalah satu-satunya orang yang bisa membuat aku tenang hanya dengan suaramu'),
(88, 'Cara kamu percaya pada proses — pada proses kita, pada waktu, pada perjalanan panjang ini'),
(89, 'Kamu adalah orang yang selalu ingin aku ajak menua bersama-sama'),
(90, 'Cara kamu mengingatkan aku untuk beristirahat saat aku terlalu keras pada diri sendiri'),
(91, 'Kamu tidak pernah membanding-bandingkan aku dengan siapapun — itu sangat berarti bagiku'),
(92, 'Cara kamu mencintai tanpa membuatku merasa terbatas atau terkekang'),
(93, 'Kamu adalah hadiah terbaik yang pernah diberikan kehidupan kepadaku'),
(94, 'Cara kamu tetap kuat dan tegar bahkan di saat kamu sendiri juga sedang berjuang'),
(95, 'Kamu membuatku percaya bahwa sesuatu yang indah dan nyata itu sungguh-sungguh ada'),
(96, 'Cara kamu memilih untuk tetap ada — setiap hari, dengan sadar, dengan penuh cinta'),
(97, 'Kamu membuat aku tidak takut lagi menghadapi masa depan, karena aku tahu kamu ada'),
(98, 'Cara kamu menaruh kepercayaan padaku — itu tanggung jawab yang aku pegang dengan sepenuh hati'),
(99, 'Kamu bukan hanya pacar aku — kamu adalah rumah yang selalu aku rindukan'),
(100, 'Dan setiap hari, aku menemukan satu alasan baru untuk semakin dalam mencintaimu');